name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-15  # Updated to newer macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'  # Use latest stable version

      - name: Debug Xcode setup
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo "Available schemes:"
          xcodebuild -project DataKit/DataKit.xcodeproj -list
          echo "Available destinations for DataKitTests:"
          xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -showdestinations

      - name: Build and run tests on macOS
        run: |
          xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -destination 'generic/platform=macOS' clean test
