name: Run DataKit macOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest # Use the latest macOS runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Debugging steps (can remove these once everything is stable)
    - name: List installed Xcode versions
      run: ls -F /Applications/ | grep "Xcode"
      continue-on-error: true

    - name: Check current Xcode version
      run: xcode-select -p
      continue-on-error: true

    - name: Select Xcode 16.2
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app

    - name: Confirm Xcode version after selection
      run: xcode-select -p

    - name: List repository contents
      run: |
        echo "Contents of GITHUB_WORKSPACE (repository root):"
        ls -F "${GITHUB_WORKSPACE}"
        echo "Contents of DataKit folder:"
        ls -F "${GITHUB_WORKSPACE}/DataKit"

    - name: Run DataKit Swift Tests
      run: |
        # Change directory into the 'DataKit' folder where your 'DataKit.xcodeproj' is located.
        cd "${GITHUB_WORKSPACE}/DataKit"

        echo "Running xcodebuild from: $(pwd)"
        xcodebuild test \
          -scheme DataKitTests \
          -project DataKit.xcodeproj \
          -destination 'platform=macOS,arch=arm64' \
          CODE_SIGN_IDENTITY="" \             # <--- ADDED
          CODE_SIGNING_REQUIRED=NO \          # <--- ADDED
          CODE_SIGNING_ALLOWED=NO \           # <--- ADDED
          ONLY_ACTIVE_ARCH=NO
