name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-15  # Updated to newer macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'  # Use latest stable version

      - name: Build and run tests on macOS
        run: |
          # Try multiple destination formats until one works
          echo "Trying name=Any Mac..."
          if ! xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -destination 'name=Any Mac' clean test; then
            echo "Failed with name=Any Mac, trying platform=macOS..."
            if ! xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -destination 'platform=macOS' clean test; then
              echo "Failed with platform=macOS, trying without destination..."
              xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKit clean test
            fi
          fi
