name: Run DataKit macOS Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest # Use the latest macOS runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step to list available Xcode versions (for debugging)
    - name: List installed Xcode versions
      run: ls -F /Applications/ | grep "Xcode"
      continue-on-error: true # Allow the workflow to continue even if this fails

    # Step to check the currently selected Xcode version (for debugging)
    - name: Check current Xcode version
      run: xcode-select -p
      continue-on-error: true

    # Explicitly select Xcode 15.4
    - name: Select Xcode 15.4
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app
      # Add a post-selection check to confirm it worked
    - name: Confirm Xcode version after selection
      run: xcode-select -p

    - name: Run DataKit Swift Tests
      run: |
        # IMPORTANT: When you use `-project DataKit/DataKit.xcodeproj`
        # in the xcodebuild command, it expects to be run from the
        # root of your repository (where the 'DataKit' folder is located).
        # The previous error message indicates xcodebuild was trying to find
        # 'DataKit.xcodeproj' inside '/Users/runner/work/DataKit/DataKit/DataKit',
        # which means it thought it was in '/Users/runner/work/DataKit/DataKit'
        # and you told it to look for 'DataKit/DataKit.xcodeproj'.
        #
        # Let's ensure the current directory is the repository root
        # and then provide the full relative path to the project.
        #
        # /Users/runner/work/DataKit/ <--- This is the repository root after checkout

        # Ensure we are at the repository root before running xcodebuild
        # The checkout action places the repo at GITHUB_WORKSPACE
        # You can use GITHUB_WORKSPACE to ensure you're in the correct base directory.
        echo "Current working directory: $(pwd)"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"

        # The correct command for your setup (project inside DataKit folder)
        # when running from the repo root is:
        xcodebuild test \
          -scheme DataKitTests \
          -project "${GITHUB_WORKSPACE}/DataKit/DataKit.xcodeproj" \
          -destination 'platform=macOS,arch=arm64' \
          ONLY_ACTIVE_ARCH=NO
