name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-15  # Updated to newer macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'  # Use latest stable version

      - name: Build and run tests on macOS
        run: |
          xcodebuild clean build test -project DataKit/DataKit.xcodeproj -scheme "DataKitTests" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
