name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-macos:
    runs-on: macos-15  # Updated to newer macOS version

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'  # Use latest stable version

      - name: Build and run tests on macOS
        run: |
          # Get current available destinations
          echo "=== Available destinations ==="
          xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -showdestinations
          
          # Extract the Mac destination ID dynamically
          MAC_ID=$(xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -showdestinations 2>/dev/null | grep "platform:macOS" | grep "My Mac" | grep -o 'id:[A-F0-9-]*' | head -1 | cut -d: -f2)
          
          if [ -z "$MAC_ID" ]; then
            echo "Could not find Mac ID, trying without ID..."
            xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -destination 'platform=macOS' clean test
          else
            echo "Using Mac ID: $MAC_ID"
            xcodebuild -project DataKit/DataKit.xcodeproj -scheme DataKitTests -destination "platform=macOS,id=$MAC_ID" clean test
          fi
