name: Run DataKit macOS Tests

on:
  push:
    branches:
      - main # Or your default branch, e.g., master, develop, if different
  pull_request:
    branches:
      - main # Or your default branch, if different

jobs:
  test-macos:
    runs-on: macos-latest # Use the latest macOS runner for your tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to checkout your repository code

    # NEW STEP: Select the specific Xcode version
    - name: Select Xcode 15.4
      run: sudo xcode-select -switch /Applications/Xcode_15.4.app

    - name: Run DataKit Swift Tests
      run: |
        xcodebuild test -scheme DataKitTests -project DataKit/DataKit.xcodeproj -destination 'platform=macOS,arch=arm64' ONLY_ACTIVE_ARCH=NO
